### ISSUE TITLE
Build error on IOS (use_frameworks!)

### ISSUE THREAD

**Issue by bandodebits** [chemerisuk/cordova-plugin-firebase-analytics#113]
The problem seems to be with the use of newer versions of Firebase.
They are incompatible with the parameter use_frameworks !, required for example by Ionic Capacitor.
The new version of Pods lets you replace use_frameworks! by use_modular_headers !, but it seems that it also does not work.
Errors are always similar to "Firebase Module not found".
The only thing that worked was to go back to the versions prior to 2.0.2 ("cordova-plugin-firebase-analytics": "^ 1.1.1", "cordova-plugin-firebase-config": "1.2.1" o "@import Firebase;" by "#import" Firebase.h "".
The problem with this solution is that we are stuck with older versions of Firebase.

**Comment by chemerisuk** [comment]
Why `use_frameworks!` is required for Capacitor?

**Comment by bandodebits** [comment]
Sadly yes.

The Capacitor automatically generates the Pod File with use_frameworks! and if you pull it out it breaks. Replace with use_modular_headers! resolves the Firebase error, but breaks cordova-firebase-analytics and cordova-firebase-config.

I even tried to override the dependency of the cordova plugin in the Pod file using a direct option in the call:
pod 'Firebase / Core',: modular_headers => true
But it still did not work out.
I had to go back to previous versions of plugins.
There are numerous topics reporting the same thing.

**Comment by bandodebits** [comment]
The Pod File

`platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  pod 'Firebase/Messaging', :modular_headers => true
end
`

**Comment by chemerisuk** [comment]
@bandodebits I suggest to open an issue in their repo so they'll explain such a requirement for Capacitor. Because it can break other plugins as well.

**Comment by mtshare** [comment]
I got this error since the last update:

`Installing "cordova-plugin-firebase-analytics" for ios
cordova-ios version check failed ("../platforms/ios/cordova/version"), continuing anyways.
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1`

**Comment by mtshare** [comment]
Fixed in the last release!!!

**Comment by chemerisuk** [comment]
@bandodebits can you check if v2.0.3 works in your project?

**Comment by bandodebits** [comment]
Unfortunately the problem still persists.

**'FirebaseCore/FirebaseCore.h' file not found**

It is related to the Firebase/Core Pod that is being imported by Cordova. Since it does not have use_modular_headers! specified, ends up conflicting with! use_frameworks! specified by the Capacitor.
The Firebase/Messaging Pod that I manually put in the Pod File, passes normally because I put the use_modular_headers parameter! on the call.

pod 'Firebase/Messaging', :modular_headers => true

I even tried to override the Firebase/Core installed by your plugin, but it also did not work.

-----------------------------------------
`platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'Firebase/Core', :modular_headers => true
end`
-----------------------------------------
![Screen Shot 2019-05-30 at 15 29 48](https://user-images.githubusercontent.com/3931241/58656546-dd6b3d00-82f2-11e9-9192-6af715e8845d.png)

**Comment by pilz97** [comment]
i have the same problem..

**Comment by bandodebits** [comment]
Any fix?

**Comment by simonpeters** [comment]
I'm running into the same issue on cordova

**Comment by mobileDev2020** [comment]
Will Google Analytics plugin stop working after Sept 30th ? So that means we have to get this alternative to start working before that ?

**Comment by Ross-Rawlins** [comment]
So is there a new release we must wait for?

**Comment by mic345** [comment]
> I got this error since the last update:
> 
> ```Installing "cordova-plugin-firebase-analytics" for ios cordova-ios version check failed ("../platforms/ios/cordova/version"), continuing anyways. Running command: pod install --verbose Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1```
> 
> `[!] Oh no, an error occurred.
> 
> Search for existing GitHub issues similar to yours:
> [https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22%24POD_FIREBASE_VERSION%22%60&type=Issues`](https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22%24POD_FIREBASE_VERSION%22%60&type=Issues%60)

Hi Maxim,

I am experiencing this issue on 4.4.1 when trying to use the plugin with capacitor. Do you happen to know if it was resolved?

Thanks!
mic.

**Comment by chemerisuk** [comment]
@mic345 ping capacitor team, I guess they do not support variables for podspec tag.

**Comment by mic345** [comment]
I'll check it out with them, thanks for the quick reply👍

**Comment by jpike88** [comment]
Still getting that error after all this time. Using cordova-plugin-firebasex instead

**Comment by chemerisuk** [comment]
Use_frameworks is required for recent firebase iOS sdk so it was added in v7
